---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: mayastor
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: mayastor-charts
        namespace: flux-system
      interval: 10m
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: -1
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    etcd:
      storageClass: "manual"
    io_engine:
      resources:
        limits:
          cpu: "350m"
        requests:
          cpu: "350m"
    loki-stack:
      enabled: false
