---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-jellyfin
  namespace: jellyfin
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume2/media
    server: 192.168.1.7
    readOnly: true
