apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-jellyfin   # < name of the persistant volume claim ("pvc'")
  namespace: jellyfin         # < namespace where place the pvc
spec:
  storageClassName: "mayastor-single-replica"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-jellyfin
  namespace: jellyfin
spec:
  storageClassName: ""
  volumeName: data-jellyfin
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1G
