---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postfinance-charts
  namespace: flux-system
spec:
  interval: 120m0s
  url: https://postfinance.github.io/kubelet-csr-approver
