---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  path: ./namespaces/base/jellyfin/jellyfin/app
  prune: false
  wait: true
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
