---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
  labels:
    substitution.flux/enabled: true
spec:
  path: ./namespaces/base/kube-system/nfs-subdir-external-provisioner/app
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: false
