apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/default
  - ../../base/default/calibre/ks.yaml
  - ../../base/flux-system/addons/ks.yaml
  - ../../base/kube-system
  - ../../base/kube-system/cilium/ks.yaml
  - ../../base/kube-system/kubelet-csr-approver/ks.yaml
  - ../../base/kube-system/metrics-server/ks.yaml
  - ../../base/kube-system/nfs-subdir-external-provisioner/ks.yaml
    #  - ../../base/network-system
    #  - ../../base/network-system/metallb/ks.yaml
  - ../../base/openebs
  - ../../base/openebs/mayastor/ks.yaml
