---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - helmrelease.yaml
  - cilium-l2.yaml

configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=./1.14.x.yaml

configurations:
  - kustomizeconfig.yaml
