---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: main@sha256:95d2920f43e8bfc08c593a9c33f3a74f7d3cb0e87c54ced317abdf499bd1b4f6
  url: oci://ghcr.io/neutralalice/manifests/k8s-gitops
  verify:
    provider: cosign
