---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: main@sha256:693633fc45e3528e768b2de497c5ceb7847be1e400ed74f4503b99781f786b74
  url: oci://ghcr.io/neutralalice/manifests/k8s-gitops
  verify:
    provider: cosign
