---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8s-gitops
  namespace: flux-system
spec:
  interval: 1m
  ref:
    tag: main@sha256:a21fb68b3d7e10f96b81624b4694e0189d4bfcf508ca09f7cb2d19229dca01a7
  url: oci://ghcr.io/neutralalice/manifests/k8s-gitops
  verify:
    provider: cosign
