---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 30m
  timeout: 10m
  path: ./namespaces/overlays/talos-0
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
