---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb
  namespace: flux-system
spec:
  path: ./namespaces/base/network-system/metallb/app
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-metallb-config
  namespace: flux-system
spec:
  path: ./namespaces/base/network-system/metallb/config
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-metallb
