---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-l2-pool
  namespace: network-system
spec:
  addresses:
    - 192.168.1.10-192.168.1.20
    - 10.69.69.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: network-system
spec:
  ipAddressPools:
    - metallb-l2-pool
