---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-repositories
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: ./namespaces/base/flux-system/addons/repositories
  prune: true
  wait: false
  sourceRef:
    kind: OCIRepository
    name: k8s-gitops
